jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set git to use LF
      run: 'git config --global core.autocrlf false

        git config --global core.eol lf

        '
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: adopt
        java-version: '11'
    - continue-on-error: true
      name: Build with Maven
      run: mvn --batch-mode test
name: Java CI (Windows)
on:
  repository_dispatch:
    types: trigger-ga___tests-windows.yml
